<?php
require __DIR__ . '/../app/src/http.php';
require __DIR__ . '/../app/src/db.php';
require __DIR__ . '/../app/src/auth.php';
require __DIR__ . '/../app/src/registration.php';
require __DIR__ . '/../app/src/rate_limit.php';

$config = require __DIR__ . '/../app/config.local.php';
apply_cors($config['allowed_origins']);

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    send_json(405, ['error' => 'Method not allowed']);
}

$body = read_json_body();
$email = trim($body['email'] ?? '');

// No username field — WordPress needs one internally, but there's no reason a visitor
// should have to invent it; create_wp_user() derives one from the email and handles any
// collision itself (see registration.php's own comment on derive_username()).
//
// No password field either, not since this was found to be entirely pointless to collect
// (raised directly, live, twice: F-061's own confusion, then "Password muss immer noch
// angegeben werden beim registrieren" after F-063 already fixed the symptom but not the
// cause). WordPress's REST API still requires *some* password to create a user with — WP
// core itself has no "passwordless account" concept — but nothing a visitor types here was
// ever going to be usable anyway: Basic Auth against the REST API only ever accepts an
// Application Password (always server-generated by WordPress itself, confirmed directly,
// not a REST API quirk closable by asking at a different step — see F-066's own
// investigation, decisions.md). A real, random value WordPress's own API requirement is
// satisfied with, never shown to anyone and never meant to authenticate anything, closes
// the actual gap instead of just hiding its symptom.
$password = bin2hex(random_bytes(24));

if ($email === '') {
    send_json(400, ['error' => 'email is required']);
}
if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
    send_json(400, ['error' => 'That doesn\'t look like a valid email address']);
}

try {
    $db = get_db($config);
    // Strict and IP-based — there's no account yet to key off of, and this is exactly
    // the endpoint D-055 flagged as needing rate limiting before it could exist at all.
    enforce_rate_limit($db, 'register:' . client_ip(), 5, 3600); // 5 registrations / hour

    $wpUser = create_wp_user($config, $email, $password);
    $token = create_unverified_user($db, $wpUser['id'], $wpUser['username']);
    send_verification_email($config, $email, $wpUser['username'], $token);

    send_json(201, ['message' => 'Check your email to confirm your account before signing in.']);
} catch (EmailAlreadyRegisteredException $e) {
    // F-059: never let this response distinguish "account created" from "that email
    // already has one" — same reasoning as forgot-password.php's own identical-response
    // rule, applied here too. Issues a fresh verification/reset token for the existing
    // account and emails it — functionally a resend, exactly what a visitor who forgot
    // they already registered actually needs — then returns the exact same 201 and
    // message a brand-new registration would.
    $wpUser = find_wp_user_by_email($config, $email);
    if ($wpUser) {
        ensure_user($db, $wpUser['id'], $wpUser['username']);
        $token = issue_password_reset_token($db, $wpUser['id']);
        send_verification_email($config, $email, $wpUser['username'], $token);
    }
    send_json(201, ['message' => 'Check your email to confirm your account before signing in.']);
} catch (RegistrationException $e) {
    send_json(400, ['error' => $e->getMessage()]);
} catch (Throwable $e) {
    error_log('register.php: ' . $e->getMessage());
    send_json(500, ['error' => 'Internal error']);
}
